### ISSUE TITLE
Не запускается парсер

### ISSUE THREAD

**Issue by VegasChickiChicki** [SergeyNikAl/VoxWeb_test#1]
При попытке запустить парсер выдает ошибку:

DevTools listening on ws://127.0.0.1:51283/devtools/browser/23726770-4e4e-4549-b424-fb781ae43452
Traceback (most recent call last):
  File "C:\work-projects\popso-backend-tests\VoxWeb_test\parser\parser.py", line 202, in <module>
  File "C:\work-projects\popso-backend-tests\VoxWeb_test\parser\parser.py", line 120, in fetch_ozon
    soup = BeautifulSoup(data, 'lxml')
  File "C:\Users\LasVegas\AppData\Local\Programs\Python\Python310\lib\site-packages\bs4\__init__.py", line 248, in __init__
    raise FeatureNotFound(
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
PS C:\work-projects\popso-backend-tests\VoxWeb_test\parser> [32476:17752:0831/152528.790:ERROR:device_event_log_impl.cc(214)] [15:25:28.791] USB: usb_service_win.cc:415 Could not read device interface GUIDs: ═х єфрхЄё  эрщЄш єърчрээ√щ Їрщы. (0x2)  
[32476:17752:0831/152528.805:ERROR:device_event_log_impl.cc(214)] [15:25:28.806] Bluetooth: bluetooth_adapter_winrt.cc:1164 RequestRadioAccessAsync failed: RadioAccessStatus::DeniedByUserWill not be able to change radio power.

**Comment by SergeyNikAl** [comment]
Обновил requirements, не были добавлены последние модули.

**Comment by SergeyNikAl** [comment]
Обновил requirements и немного поправил сам парсер. Перезалил в репозиторий.
Не были добавлены последние модули
